# Generated by Django 4.0.4 on 2022-05-14 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hid', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('by', models.CharField(blank=True, max_length=256, null=True)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=256)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
    ]
