# Generated by Django 4.0.4 on 2022-05-10 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=256)),
                ('descendants', models.IntegerField()),
                ('kids', models.CharField(max_length=512, validators=[django.core.validators.int_list_validator])),
                ('score', models.IntegerField()),
                ('time', models.BigIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('item_type', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=512)),
            ],
        ),
    ]
