# Generated by Django 4.0.4 on 2022-05-10 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_text_alter_item_descendants_alter_item_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dead',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='parts',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
