# Generated by Django 4.0.4 on 2022-05-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_dead_item_deleted_item_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
