# Generated by Django 4.0.4 on 2022-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
