# Generated by Django 4.0.4 on 2022-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_kids_alter_item_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hid',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
