# Generated by Django 4.0.4 on 2022-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_hid_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hid',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
